---
title: "Contraception report"
author: Darwin Del Castillo & Natalia Valverde
format: docx
editor: source
editor_options:
  chunk_output_type: console
---
```{r setup}
#| name: setup
#| include: false
#| warning: false
knitr::opts_chunk$set(echo = FALSE, comment = "", results = 'asis')
options(scipen = 999999)
```

```{r}
#| name: packages
#| include: false
pacman::p_load(
  lme4,
  lmerTest,
  gtsummary,
  flextable,
  cardx
)
```


```{r}
#| name: data cleaning
#| include: false
#| warning: false
source("code/data_cleaning.R")
```

```{r}
#| name: data description
#| include: true
#| warning: false

# Tabla general
tabla_1 <- data_clean |>
  tbl_summary(
    by = provincia,
    include = c("edad", "estado_civil", "educacion_agrupado", "religion",
                "etnia_identificador", "etnia", "post_aborto_anticoncep",
                "limitacion_economica"), # variables relevantes
    missing = "no",
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n} ({p}%)"),
    digits = list(all_continuous() ~ c(1, 0),
                  all_categorical() ~ c(0, 1)),
    label = list(
      edad ~ "Edad",
      estado_civil ~ "Estado civil",
      educacion_agrupado ~ "Nivel educativo",
      religion ~ "Religión",
      etnia ~ "Etnia",
      etnia_identificador ~ "Se identifica con una etnia",
      post_aborto_anticoncep ~ "Uso de anticonceptivos post aborto",
      limitacion_economica ~ "Limitaciones económicas")
  ) |>
  add_stat_label(
    label = list(
      all_continuous() ~ "Media (DE)",
      all_categorical() ~ "n (%)"
    )
  )
```

`r tabla_1`

```{r}
#| name: data analysis
#| include: false
#| warning: false

# Model 1: Contraception use and age
model_1 <- glmer(
  post_aborto_anticoncep ~
    edad +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_1))

# Model 2: Contraception use and estado civil
model_2 <- glmer(
  post_aborto_anticoncep ~
    estado_civil +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_2))

# Model 3: Contraception use and religion
model_3 <- glmer(
  post_aborto_anticoncep ~
    religion +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_3))

# Model 4: Contraception use and etnia
model_4 <- glmer(
  post_aborto_anticoncep ~
    etnia_identificador +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_4))

# Model 5: Contraception use and nivel educativo
model_5 <- glmer(
  post_aborto_anticoncep ~
    educacion_agrupado +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_5))

# Model 6: Contraception use and limitaciones economicas
model_6 <- glmer(
  post_aborto_anticoncep ~
    limitacion_economica +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_6))

# Model 7: Contraception use and embarazo planificado
model_7 <- glmer(
  post_aborto_anticoncep ~
    embarazo_planificado +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_7))

```


```{r}
#| name: data analysis multivariate
#| include: false
#| warning: false

# Model 1 Multivariate: edad + estado_civil + religion + etnia + educacion
model_1_multivariate <- glmer(
  post_aborto_anticoncep ~
    edad +
    estado_civil +
    religion +
    etnia_identificador +
    educacion_agrupado +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

# Model 2 Multivariate: edad + estado_civil + religion + etnia + educacion + limitacion economica + embarazo planificado
model_2_multivariate <- glmer(
  post_aborto_anticoncep ~
    edad +
    estado_civil +
    religion +
    etnia_identificador +
    educacion_agrupado +
    limitacion_economica +
    embarazo_planificado +
    (1 | provincia / distrito),
  data = data_clean,
  family = poisson(link = "log"),
  control = glmerControl(optimizer = "bobyqa")
)

exp(fixef(model_2_multivariate))

```

```{r}
#| name: tabla 2
#| include: true
#| warning: false

tbl_edad <- tbl_regression(model_1, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Crudo**") |>
  modify_footnote(estimate ~ "PR = Incidence Rate Ratio") |>
  bold_labels()

tbl_estado_civil <- tbl_regression(model_2, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Crudo**") |>
  bold_labels()

tbl_religion <- tbl_regression(model_3, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Crudo**") |>
  bold_labels()

tbl_etnia <- tbl_regression(model_4, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Crudo**") |>
  bold_labels()

tbl_educacion <- tbl_regression(model_5, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Crudo**") |>
  bold_labels()

tbl_limitacion <- tbl_regression(model_6, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Crudo**") |>
  bold_labels()

tbl_embarazo <- tbl_regression(model_7, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Crudo**") |>
  bold_labels()

# Crear tabla del modelo ajustado
tbl_ajustado_1 <- tbl_regression(model_1_multivariate, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Ajustado**") |>
  bold_labels()

tbl_ajustado_2 <- tbl_regression(model_2_multivariate, exponentiate = TRUE) |>
  modify_header(estimate ~ "**PR Ajustado**") |>
  bold_labels()

# Combinar todas las tablas
tabla_combinada <- tbl_merge(
  list(tbl_edad, tbl_ajustado_1, tbl_ajustado_2),
  tab_spanner = c("**Modelo Univariado**", "**Modelo Multivariado 1**", "**Modelo Multivariado 2**")
)

```

\newpage
`r tabla_combinada`