# ---
# Data cleaning
# Author: Darwin Del Castillo
# Date: `r Sys.Date()`
# ---

# Load necessary libraries
pacman::p_load(tidyverse, 
               janitor,
               stringr,
               readxl)

##### Loading data #####
# Load the data
data_raw <- read_xlsx(path = "data/raw/data_final_raw.xlsx",
                               sheet = "BASE 900 CODIFICADA",
                               range = "A1:CX901",
                               col_names = TRUE,
                               na = c("", "NA")) |>
  clean_names() |>
  ## Creating column with number of row as values
  mutate(index = row_number())

data_identifiers <- read_xlsx(path = "data/raw/data_final_raw.xlsx",
                              sheet = "DATA 890",
                              range = "A1:DK901",
                              col_names = TRUE,
                              na = c("", "NA")) |> 
  clean_names() |> select(-index) |>
  mutate(index = row_number()) |>
  select(index, id)

## Joint ids with data_raw keeping ids at the beginning of the dataset
data_mid <- data_raw |>
  left_join(data_identifiers, by = "index") |>
  select(id, everything()) |>
  select(-index)

## Removing intermediate databases
rm(data_identifiers, data_raw)

##### Data cleaning #####
# Changing names of variables to something more readable
data_mid <- data_mid |>
  rename(
    codigo_encuestador = codigo_de_encuestador,
    edad = que_edad_tiene,
    estado_civil = que_estado_civil_tiene,
    educacion = cual_es_su_nivel_educativo,
    ocupacion = a_que_se_dedica,
    educacion_agrupado = nivela_grupado,
    provincia = en_que_provincia_vive,
    distrito = en_que_distrito_vive,
    etnia_identificador = se_identifica_con_alguna_comunidad_nativa_o_poblacion_etnica,
    etnia = si_marca_si_cual_es,
    religion = pertenece_a_alguna_religion,
    religion_otra = otro_mencione_cual_13,
    celular = cuenta_con_un_celular_para_comunicarse,
    celular_wsp = el_celular_cuenta_con_el_aplicativo_por_whats_app,
    internet_identificador = cuenta_con_internet_en_su_celular_las_24_hrs,
    internet_tiempo = en_que_horario_cuenta_con_internet,
    embarazada_identificador = has_estado_alguna_vez_embarazada,
    hijos_numero = cuantos_hijos_tiene,
    ultima_gestacion = como_concluyo_su_ultima_gestacion,
    ult_embarazo_fecha = cuando_fue_su_ultimo_embarazo,
    tiene_pareja = actualmente_tiene_una_pareja,
    tiempo_pareja = cuanto_tiempo_de_relacion_tienes_con_tu_pareja,
    plan_familiar_ident = actualmente_usas_algun_metodo_de_planificacion_familiar,
    plan_familiar_why = cual_es_la_razon_principal_por_la_cual_no_utilizas_un_metodo_anticonceptivo,
    plan_familiar_otro = otro_mencione,
    met_contra = que_metodo_anticonceptivo_utiliza_actualmente,
    met_contra_donde = de_donde_obtiene_su_metodo_anticonceptivo_actualmente,
    met_contra_otro = otro_mencione_2,
    pareja_met_contra = tu_pareja_sabe_que_usas_un_metodo_anticonceptivo,
    pareja_met_contra_a = tu_pareja_esta_de_acuerdo_con_que_utilices_un_metodo_anticonceptivo,
    pareja_met_decide = tu_pareja_toma_la_ultima_decision_para_que_utilices_un_metodo_anticonceptivo,
    p_dia_siguiente = alguna_vez_has_tomado_la_pastilla_del_dia_siguiente,
    ultima_p_dia_siguiente = cuando_fue_la_ultima_vez_que_tomaste_esa_pastilla,
    cuantas_p_dia_siguiente = cuantas_veces_en_un_ano_has_tomado_esa_pastilla,
    post_p_anticoncep = posterior_a_esa_ultima_toma_decidiste_utilizar_un_metodo_anticonceptivo,
    serv_plani_fam = alguna_vez_acudio_a_un_consultorio_de_planificacion_familiar_en_un_puesto_de_salud_u_hospital,
    motiv_plani_fam = cual_fue_el_motivo_principal_de_que_no_acudieras_al_consultorio_de_planificacion_familiar,
    motiv_plani_fam_o = otro_mencione_cual_39,
    tiempo_plani_fam = cuanto_tiempo_tuvo_que_esperar_para_recibir_la_atencion,
    horario_propuesta = cual_seria_su_propuesta_de_horario_de_atencion,
    prof_salud_amable = el_profesional_de_salud_que_le_brindo_la_atencion_sobre_planificacion_familiar_fue_amable,
    consejeria_privada = el_lugar_donde_se_te_brindo_consejeria_sobre_planificacion_familiar_fue_en_un_ambiente_privado,
    info_comprension = comprendio_la_informacion_que_le_brindo_el_profesional_de_salud,
    atencion_calificacion = como_calificaria_la_atencion_del_profesional_de_salud,
    atencion_mala_motivo = si_marca_mala_o_regular_porque,
    atencion_otro_motivo = si_marco_otro_cual_fue_el_motivo_48,
    info_medio_pref = por_que_medio_preferiria_recibir_informacion_sobre_planificacion_familiar,
    x50 = x50,
    info_correo = por_que_medio_preferiria_recibir_informacion_sobre_planificacion_familiar_correo_electronico,
    info_telefono = por_que_medio_preferiria_recibir_informacion_sobre_planificacion_familiar_llamada_telefonica,
    info_whatsapp = por_que_medio_preferiria_recibir_informacion_sobre_planificacion_familiar_whats_app,
    info_redes = por_que_medio_preferiria_recibir_informacion_sobre_planificacion_familiar_facebook_o_instagram,
    info_presencial = por_que_medio_preferiria_recibir_informacion_sobre_planificacion_familiar_de_manera_presencial_charlas_visitas_etc,
    info_otro = por_que_medio_preferiria_recibir_informacion_sobre_planificacion_familiar_otro,
    info_otro_cual = mencione_cual_57,
    perdidas_identificador = ha_tenido_perdidas_en_algun_momento,
    perdidas_numero = cuantas_perdidas,
    perdidas_tiempo = hace_cuanto_tiempo,
    pre_aborto_anticoncep = utilizabas_algun_metodo_de_planificacion_familiar_antes_del_aborto,
    no_anticoncep_motivo = si_marca_no_cual_fue_el_motivo_principal_del_por_que_no_decidiste_usar_algun_metodo,
    no_anticoncep_otro = si_marco_otro_cual_fue_el_motivo_63,
    pre_aborto_metodo = que_metodo_anticonceptivo_utilizabas_antes_del_aborto,
    aborto_busco_ayuda = cuando_tuviste_el_aborto_buscaste_ayuda_en_algun_establecimiento_de_salud,
    no_ayuda_motivo = cual_fue_el_motivo_principal_del_por_que_no_buscaste_ayuda,
    no_ayuda_otro = si_marco_otro_cual_fue_el_motivo,
    establecimiento_tipo = en_que_tipo_de_establecimiento_de_salud,
    establecimiento_otro = otro_especifique,
    tiempo_atencion_aborto = cuanto_tiempo_tuvo_que_esperar_para_su_atencion_por_el_aborto_en_el_establecimiento_de_salud,
    traslado_modo = como_se_traslado_hasta_el_establecimiento_de_salud_mas_cercano,
    problema_atencion = tuviste_algun_problema_para_atender_tu_aborto,
    problema_tipo = si_marca_si_cual_es_el_principal_problema_que_tuvo,
    problema_especifico = especifique_que_tipo_de_problema,
    post_aborto_anticoncep = inmediatamente_luego_del_aborto_decidiste_utilizar_un_metodo_anticonceptivo,
    no_anticoncep_razon = cual_fue_la_razon_principal_del_por_que_no_decidiste_usar_algun_metodo,
    no_anticoncep_cual = mencione_cual_77,
    anticoncep_tiempo = cuanto_tiempo_paso_desde_el_aborto_hasta_que_iniciaste_a_usar_un_metodo_anticonceptivo,
    anticoncep_metodo = que_metodo_aceptaste_utilizar_luego_del_aborto,
    metodo_preferido = aquel_metodo_que_utilizaste_fue_el_metodo_que_realmente_querias_utilizar,
    metodo_preferencia = que_metodo_anticonceptivo_hubiera_preferido_utilizar,
    no_metodo_razon = cual_fue_la_razon_principal_por_la_que_no_llego_a_utilizar_el_metodo_que_usted_preferia,
    no_metodo_cual = mencione_cual_83,
    metodo_origen = el_metodo_anticonceptivo_que_utilizo_luego_del_aborto_de_donde_lo_obtuvo,
    metodo_influencia = quien_ha_influido_mas_en_la_eleccion_definitiva_del_metodo_utilizado,
    consejeria_aborto = recibio_consejeria_sobre_planificacion_familiar_cuando_tuvo_su_aborto,
    consejeria_momento = en_que_momento_recibio_consejeria_en_planificacion_familiar,
    embarazo_posible_info = el_profesional_de_salud_le_menciono_que_es_posible_que_quede_embarazada_2_semanas_luego_del_aborto,
    consejeria_lugar = en_donde_recibio_consejeria_en_planificacion_familiar_luego_del_aborto,
    consejeria_privacidad = el_lugar_donde_se_te_brindo_asesoria_sobre_planificacion_familiar_luego_del_aborto_fue_en_un_ambiente_privado,
    profesional_amabilidad = el_profesional_de_salud_que_le_brindo_la_consejeria_sobre_planificacion_familiar_post_aborto_fue_amable,
    metodos_explicacion = el_profesional_de_salud_que_le_brindo_la_consejeria_sobre_planificacion_familiar_le_explico_ventajas_y_desventajas_de_los_metodos_anticonceptivos,
    metodos_comprension = si_marca_si_usted_comprendio_la_informacion_sobre_los_metodos_anticonceptivos_que_le_brindo_el_profesional_de_salud,
    limitacion_economica = tuviste_alguna_limitacion_economica_para_utilizar_metodos_anticonceptivos_despues_del_aborto,
    religion_influencia = la_religion_influyo_en_tu_decision_de_utilizar_metodos_anticonceptivos_despues_del_aborto,
    cultura_limitacion = tus_creencias_culturales_fue_una_limitacion_para_usar_metodos_anticonceptivos_despues_del_aborto,
    atencion_calidad = considera_que_la_atencion_ofrecida_sobre_planificacion_familiar_post_aborto_fue,
    satisfaccion_nivel = su_grado_de_satisfaccion_con_la_atencion_de_planificacion_familiar_postaborto_fue,
    embarazo_posterior = tuviste_alguna_gestacion_posterior_a_su_aborto,
    embarazo_tiempo = cuanto_tiempo_posterior_al_aborto_quedo_embarazada,
    embarazo_planificado = si_dice_que_si_ese_embarazo_fue_planificado,
    embarazo_culminacion = como_culmino_ese_embarazo
  ) |>
  mutate(religion = factor(religion, 
                          levels = c("0", "1", "2", "3"),
                          labels = c("Evangélica", 
                                     "Católica",
                                     "Otros/Ninguna",
                                     "Otros/Ninguna")),
         estado_civil = factor(estado_civil,
                              levels = c("0", "1", "2", "3", "4"),
                              labels = c("Soltera/Separada/Viuda",
                                         "Casada/Conviviente",
                                         "Casada/Conviviente",
                                         "Soltera/Separada/Viuda",
                                         "Soltera/Separada/Viuda")),
         etnia_identificador = factor(etnia_identificador,
                                    levels = c("0", "1"),
                                    labels = c("Si", "No")),
         etnia = factor(etnia,
                      levels = c("0", "1", "2", "3"),
                      labels = c("Quechua", "Otros", "Otros", "Otros")),
         provincia = factor(provincia,
                                levels = c("0", "1", "2"),
                                labels = c("Huánuco",
                                           "Leoncio Prado",
                                           "Yarowilca")),
         distrito = factor(distrito,
                          levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9"),
                          labels = c("Huánuco",
                                     "Amarilis",
                                     "Pillcomarca",
                                     "Chavinillo",
                                     "Cahuac",
                                     "Jacas Chico",
                                     "Pumahuasi",
                                     "Luyando",
                                     "Hermilio Valdizan",
                                     "Rupa Rupa")),
         plan_familiar_ident = factor(plan_familiar_ident,
                            levels = c("0", "1"),
                            labels = c("No", "Si")),
         serv_plani_fam = factor(serv_plani_fam,
                            levels = c("0", "1"),
                            labels = c("No",
                                       "Si")),
         limitacion_economica = factor(limitacion_economica,
                            levels = c("0", "1"),
                            labels = c("Si",
                                       "No")),
         embarazo_planificado = factor(embarazo_planificado,
                            levels = c("0", "1"),
                            labels = c("No",
                                       "Si")),
         educacion_agrupado = factor(educacion_agrupado,
                            levels = c("0", "1", "2", "3", "4"),
                            labels = c("Sin instrucción",
                                       "Básica",
                                       "Básica",
                                       "Superior",
                                       "Superior")),
         pre_aborto_anticoncep = factor(pre_aborto_anticoncep, 
                            levels = c(0, 1), 
                            labels = c("No", "Sí")),
         post_aborto_anticoncep = factor(post_aborto_anticoncep,
                            levels = c(0, 1), 
                            labels = c("No", "Sí")),
         ocupacion = factor(ocupacion,
                            levels = c("0", "1", "2", "3"),
                            labels = c("Estudiante",
                                       "Ama de casa",
                                       "Trabajadora independiente",
                                       "Trabajadora dependiente")),
         religion_influencia = factor(religion_influencia,
                            levels = c("1", "0"),
                            labels = c("No", "Si")),
         cultura_limitacion = factor(cultura_limitacion,
                            levels = c("1", "0"),
                            labels = c("No", "Si")),
         aborto_busco_ayuda = factor(aborto_busco_ayuda,
                            levels = c("0", "1"),
                            labels = c("No", "Si")),
         problema_atencion = factor(problema_atencion,
                            levels = c("0", "1"),
                            labels = c("Si", "No")),
         consejeria_aborto = factor(consejeria_aborto,
                            levels = c("0", "1"),
                            labels = c("No", "Si")),
         atencion_calidad = factor(atencion_calidad,
                            levels = c("0", "1", "2", "3"),
                            labels = c("Insuficiente",
                                       "Regular",
                                       "Buena",
                                       "Excelente")),
          establecimiento_tipo = factor(establecimiento_tipo,
                            levels = c("0", "1"),
                            labels = c("Privado",
                                       "Público"))
         )
